name = "threatfox-daily-c2"
main = "src/entry.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-07-06"

kv_namespaces = [
    { binding = "threatfoxiocs", id = "0efb46385b434026acc60d812549e16f" }
]

vars = { MAX_IOC_TO_COMPUTE = "10" }

# Cron does not appear to be supported on Python yet
#[triggers]
#crons = ["53 * * * *"]  # Every hour at minute 53

[placement]
mode = "smart"

[env.dev]
kv_namespaces = [
    { binding = "threatfoxiocs", id = "0efb46385b434026acc60d812549e16f" }
]
vars = { MAX_IOC_TO_COMPUTE = "1" }


[dev]
port = 37959